[project]
name = "unit-converter"
version = "1.0.0"
description = "Unit Converter is a web application for converting between different units of measurement."
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest",
]
